[package]
name = "feedlizard-app"
version.workspace = true
edition = "2024"
rust-version = "1.92"
license = "MPL-2.0"
publish = false

[[bin]]
name = "feedlizard"
path = "src/main.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.9.2", features = ["v1_9", "gtk_v4_22"] }
chrono = "0.4.45"
feedlizard-core = { path = "../feedlizard-core" }
feedlizard-image = { path = "../feedlizard-image" }
feedlizard-integration = { path = "../feedlizard-integration" }
feedlizard-network = { path = "../feedlizard-network" }
feedlizard-nostr-backup = { path = "../feedlizard-nostr-backup" }
feedlizard-reader = { path = "../feedlizard-reader" }
feedlizard-refresh = { path = "../feedlizard-refresh" }
feedlizard-storage = { path = "../feedlizard-storage" }
gtk = { package = "gtk4", version = "0.11.4", features = ["gnome_50"] }
tokio = { version = "1.47.1", features = ["rt", "time"] }
url = "2.5"
